Repository bazelbuild/rules_swift, pull requests merged in 2019-06, with the labels that each got.

#250 Fix iterating over depsets
  swift/internal/utils.bzl
Labels: cla: no

#249 Completely remove the `SwiftClangModuleInfo` provider.
  swift/internal/attrs.bzl
  swift/internal/legacy_swift_clang_module_info_aspect.bzl
  swift/internal/providers.bzl
  swift/swift.bzl
Labels: cla: yes

#251 Update docs to the last release state.
  doc/api.md
  doc/providers.md
Labels: cla: yes

#252 Use yaml anchors, aliases, and merge to avoid repetition.
  .bazelci/presubmit.yml
Labels: cla: yes

#253 Use the correct error stream in persistent mode.
  tools/worker/swift_runner.cc
Labels: cla: yes

#255 Make `swift_module_alias` not print a warning.
  swift/internal/swift_module_alias.bzl
Labels: cla: yes

#254 Internal cleanup.
  swift/internal/linking.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_toolchain.bzl
Labels: cla: yes

#256 Make sure ephemeral module caches are created inside $TMPDIR.
  tools/common/temp_file.h
Labels: cla: yes

#260 Add cc_library deps to the force_load list if they have a .lo extension
  swift/internal/compiling.bzl
Labels: Import Ready, cla: yes

#261 Rollback of commit bf376ebec2c0328b207769f41b591a0873883879
  swift/internal/compiling.bzl
Labels: cla: yes

#262 Add an aspect and script to collect timing information for Swift builds.
  swift/internal/api.bzl
  swift/internal/derived_files.bzl
  swift/internal/features.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_grpc_library.bzl
  swift/internal/swift_library.bzl
  swift/internal/swift_module_alias.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
  swift/internal/utils.bzl
  swift/stats.bzl
  tools/compile_stats/README.md
  tools/compile_stats/build.sh
Labels: cla: yes

#263 Add a report generator to the compile stats collector.
  swift/stats.bzl
  tools/compile_stats/BUILD
  tools/compile_stats/README.md
  tools/compile_stats/build.sh
  tools/compile_stats/main.swift
Labels: cla: yes

#264 Have swift_module_alias correctly set the module name in the SwiftInfo provider it creates
  swift/internal/swift_module_alias.bzl
Labels: cla: no

#265 Use an explicit loop instead of xargs when collecting compile stats.
  tools/compile_stats/build.sh
Labels: cla: yes
