Repository bazelbuild/rules_swift, pull requests merged in 2019-08, with the labels that each got.

#272 Refactor (and properly support) link stamping for Swift binaries.
  swift/internal/linking.bzl
  swift/internal/providers.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#273 Rollback of commit a00d8558d868f75632cdb980c76a38a1405a9a68
  swift/internal/linking.bzl
  swift/internal/providers.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#274 Bump apple_support to 0.7.0.
  swift/repositories.bzl
Labels: cla: yes

#275 Refactor (and properly support) link stamping for Swift binaries.
  swift/internal/linking.bzl
  swift/internal/providers.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#276 Rollback of commit f0c12e6354cf6bd7d8a8e56200cff03e9965f6e1
  swift/internal/linking.bzl
  swift/internal/providers.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: no

#277 Refactor (and properly support) link stamping for Swift binaries.
  swift/internal/linking.bzl
  swift/internal/providers.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#278 Bump skylib to 0.9.0
  swift/repositories.bzl
Labels: cla: yes

#280 Bump swift-protobuf to 1.6.0
  swift/repositories.bzl
Labels: cla: yes

#279 Bump apple_support to 0.7.1
  swift/repositories.bzl
Labels: cla: yes

#282 Update the docs.
  doc/api.md
  doc/aspects.md
  doc/providers.md
  doc/rules.md
Labels: cla: yes

#283 Add descriptor.proto to the list of bundled proto files.
  swift/internal/swift_protoc_gen_aspect.bzl
Labels: cla: yes

#284 Set -target for swift modulewrap.
  swift/internal/debugging.bzl
Labels: cla: no

#289 Make sure that embedded runtimes are also included in the inputs of the link action.
  swift/internal/linking.bzl
Labels: cla: yes

#292 Add Bazel's `-bin` output directory to the quote include paths searched by ClangImporter.
  swift/internal/api.bzl
Labels: cla: yes

#293 Just pass a name, not a target.
  swift/internal/swift_protoc_gen_aspect.bzl
Labels: cla: yes

#295 Expand the example to include WKT usage.
  examples/xplatform/proto/BUILD
  examples/xplatform/proto/example.proto
  examples/xplatform/proto/main.swift
Labels: cla: yes

#294 Remove reference to non-existent `includes` attribute in `swift_c_module` implementation.
  swift/internal/swift_c_module.bzl
  swift/internal/utils.bzl
Labels: cla: yes

#297 Disable index_while_building when providing -index-store-path
  swift/internal/compiling.bzl
Labels: Import Ready, cla: yes

#299 Use WKTs from the example.
  examples/xplatform/grpc/BUILD
  examples/xplatform/grpc/client_main.swift
  examples/xplatform/grpc/echo.proto
Labels: cla: yes
