Repository bazelbuild/rules_swift, pull requests merged in 2019-10, with the labels that each got.

#322 Factor out common output group logic into a helper function.
  swift/internal/compiling.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_grpc_library.bzl
  swift/internal/swift_library.bzl
  swift/internal/swift_module_alias.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
Labels: cla: yes

#324 Update SwiftProtobuf
  swift/repositories.bzl
Labels: Import Ready, cla: yes

#326 Update skylib to 1.0.2
  swift/repositories.bzl
Labels: cla: yes

#327 Update apple_support to 0.7.2
  swift/repositories.bzl
Labels: cla: yes

#330 Reformat all .bzl files to 80 columns and make doc comments consistent (4-space indent under Args/Returns, 4 characters between start of list bullet/number and list item text, use backslash after leading triple-quote in doc attributes to remove an unnecessary line break).
  swift/BUILD
  swift/internal/actions.bzl
  swift/internal/api.bzl
  swift/internal/attrs.bzl
  swift/internal/compiling.bzl
  swift/internal/debugging.bzl
  swift/internal/derived_files.bzl
  swift/internal/features.bzl
  swift/internal/linking.bzl
  swift/internal/non_swift_target_aspect.bzl
  swift/internal/proto_gen_utils.bzl
  swift/internal/providers.bzl
  swift/internal/swift_autoconfiguration.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_c_module.bzl
  swift/internal/swift_grpc_library.bzl
  swift/internal/swift_import.bzl
  swift/internal/swift_library.bzl
  swift/internal/swift_module_alias.bzl
  swift/internal/swift_proto_library.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/swift_usage_aspect.bzl
  swift/internal/utils.bzl
  swift/internal/xcode_swift_toolchain.bzl
  swift/repositories.bzl
  swift/stats.bzl
Labels: cla: yes

#331 Fix the `TOOLCHAINS` env var for custom Xcode toolchains.
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#332 Remove some workarounds that no longer apply for old bugs.
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#333 Make the actual output of a `swift_test` target the `.xctest` bundle (for Xcode toolchains, when the feature is not disabled).
  swift/internal/swift_binary_test.bzl
  tools/xctest_runner/xctest_runner.sh.template
Labels: cla: yes

#335 Remove CI tests for versioned releases of Bazel and dependencies.
  .bazelci/presubmit.yml
  .bazelci/update_workspace_to_deps_heads.sh
  README.md
  swift/repositories.bzl
Labels: cla: yes

#334 Avoid introducing duplicate entries in the import search path when there are multiple swiftmodules in a single directory
  swift/internal/compiling.bzl
Labels: cla: no

#313 Update `swift_{binary,test}` to use `cc_common.link`.
  swift/internal/linking.bzl
  swift/internal/providers.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#337 Internal change.
  swift/internal/linking.bzl
  swift/internal/swift_binary_test.bzl
Labels: cla: yes

#339 Add an analysis test rule to check the values of file-based provider fields.
  test/rules/BUILD
  test/rules/provider_test.bzl
Labels: cla: yes

#340 Strengthen provider_test:
  test/rules/provider_test.bzl
Labels: cla: yes

#342 More provider_test fixes:
  test/rules/provider_test.bzl
Labels: cla: yes

#343 config_settings must default to {}, not None.
  test/rules/provider_test.bzl
Labels: cla: yes

#341 Add support for implementation-only imports via the `private_deps` attribute when using Swift 5.1 or higher.
  swift/internal/attrs.bzl
  swift/internal/features.bzl
  swift/internal/swift_autoconfiguration.bzl
  swift/internal/swift_library.bzl
  swift/internal/utils.bzl
  swift/internal/xcode_swift_toolchain.bzl
  test/BUILD
  test/fixtures/BUILD
  test/fixtures/common.bzl
  test/fixtures/private_deps/BUILD
  test/fixtures/private_deps/Empty.swift
  test/fixtures/private_deps/private.h
  test/fixtures/private_deps/public.h
  test/private_deps_tests.bzl
Labels: cla: yes
