Repository bazelbuild/rules_swift, pull requests merged in 2019-04, with the labels that each got.

#166 Remove unused import.
  swift/repositories.bzl
Labels: cla: yes

#170 Remove the CODEOWNERS file.
  CODEOWNERS
Labels: cla: yes

#171 Make `swift_grpc_library` available to Bazel users.
  examples/xplatform/grpc/BUILD
  examples/xplatform/grpc/client_main.swift
  examples/xplatform/grpc/client_unit_test.swift
  examples/xplatform/grpc/echo.proto
  examples/xplatform/grpc/server_main.swift
  swift/internal/swift_grpc_library.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
  swift/repositories.bzl
  swift/swift.bzl
  third_party/com_github_apple_swift_protobuf/BUILD.overlay
  third_party/com_github_grpc_grpc_swift/BUILD.overlay
Labels: cla: yes

#172 Update the comment with better status.
  .bazelci/presubmit.yml
Labels: Import Ready, cla: yes

#173 Update the docs.
  doc/api.md
  doc/providers.md
  doc/rules.md
Labels: cla: yes

#174 Add a persistent worker to support `swiftc` incremental compilation.
  README.md
  swift/internal/api.bzl
  swift/internal/compiling.bzl
  swift/internal/derived_files.bzl
  swift/internal/providers.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/wrappers.bzl
  swift/internal/xcode_swift_toolchain.bzl
  swift/repositories.bzl
  third_party/bazel_protos/BUILD
  third_party/bazel_protos/README.md
  third_party/bazel_protos/worker_protocol.proto
  third_party/com_github_nlohmann_json/BUILD.overlay
  tools/common/BUILD
  tools/common/file_system.cc
  tools/common/file_system.h
  tools/common/path_utils.cc
  tools/common/path_utils.h
  tools/common/process.cc
  tools/common/process.h
  tools/common/string_utils.cc
  tools/common/string_utils.h
  tools/common/temp_file.h
  tools/worker/BUILD
  tools/worker/main.cc
  tools/worker/output_file_map.cc
  tools/worker/output_file_map.h
  tools/worker/work_processor.cc
  tools/worker/work_processor.h
  tools/wrappers/swift_wrapper.sh
Labels: cla: yes

#175 Add some for_bazel_tests targets to keep things complete.
  tools/BUILD
  tools/common/BUILD
  tools/worker/BUILD
Labels: cla: yes

#176 Create a "dummy worker" for upstream integration tests.
  tools/worker/BUILD
  tools/worker/dummy_main.cc
Labels: cla: yes

#178 Fix unused function warning on Linux
  tools/worker/work_processor.cc
Labels: Import Ready, cla: yes

#179 Convert to struct fields in post-cleanup APIs
  swift/internal/compiling.bzl
  swift/internal/linking.bzl
Labels: cla: no

#180 API cleanup: Remove compile_options field from SwiftInfo and remove SwiftBinaryInfo.
  swift/internal/api.bzl
  swift/internal/providers.bzl
  swift/internal/swift_binary_test.bzl
  swift/swift.bzl
Labels: cla: yes

#182 Pass all tools as 'tools' and not 'inputs'.
  swift/internal/swift_grpc_library.bzl
Labels: cla: yes

#183 Use `to_list()` for depset iteration.
  swift/internal/compiling.bzl
Labels: cla: yes

#185 Make the Swift module cache path explicitly different from Clang's.
  swift/internal/api.bzl
  swift/internal/swift_binary_test.bzl
Labels: cla: yes

#188 Show the build status only for the master branch.
  README.md
Labels: cla: yes

#187 API cleanup for `SwiftInfo` helper methods.
  swift/internal/api.bzl
  swift/internal/deps.bzl
  swift/internal/providers.bzl
  swift/internal/swift_import.bzl
  swift/internal/swift_info_through_non_swift_targets_aspect.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
Labels: cla: yes

#191 Fix CgRPC linker warnings
  third_party/com_github_grpc_grpc_swift/BUILD.overlay
Labels: Import Ready, cla: yes

#193 Add `malloc` attribute to `swift_binary`.
  swift/internal/deps.bzl
  swift/internal/swift_binary_test.bzl
Labels: cla: yes

#195 Use the C++ toolchain to register static archive actions.
  swift/internal/api.bzl
  swift/internal/archiving.bzl
  swift/internal/providers.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#196 Rollback of commit 522cd9d4e8f88fb5caac2945b3f6d38bd0cddba3
  swift/internal/api.bzl
  swift/internal/archiving.bzl
  swift/internal/providers.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#197 Use the C++ toolchain to register static archive actions.
  swift/internal/api.bzl
  swift/internal/archiving.bzl
  swift/internal/providers.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#189 Automated g4 rollback of commit b1c51a16cf12ee6723786d476ff4a498edc9a3a5.
  tools/wrappers/swift_wrapper.sh
Labels: cla: yes

#198 Support -debug-prefix-map for Xcode 10.2 (Swift 5.0) and higher.
  swift/internal/api.bzl
  swift/internal/xcode_swift_toolchain.bzl
  tools/wrappers/swift_wrapper.sh
Labels: cla: yes

#199 Fix filenames with spaces after switching to the CROSSTOOL archive action.
  swift/internal/derived_files.bzl
Labels: cla: yes

#200 Work around a bug in DottedVersion.compare_to.
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#194 Use cpp command-line linkopts during final link
  swift/internal/swift_binary_test.bzl
Labels: Import Ready, cla: yes

#202 Use to_list() for depset iteration.
  swift/internal/linking.bzl
Labels: cla: yes

#203 Disable -Wunused-function for BoringSSL
  third_party/com_github_grpc_grpc_swift/BUILD.overlay
Labels: Import Ready, cla: yes

#204 Fix comment typo
  third_party/com_github_grpc_grpc_swift/BUILD.overlay
Labels: Import Ready, cla: yes
