Repository bazelbuild/rules_swift, pull requests merged in 2019-05, with the labels that each got.

#205 Create a new `swift_common.compile` API to replace the existing two compilation APIs (`compile_as_library` and `compile_as_objects`).
  swift/internal/api.bzl
  swift/internal/archiving.bzl
  swift/internal/compiling.bzl
  swift/internal/linking.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/utils.bzl
Labels: cla: yes

#206 Migrate `swift_module_alias` to `swift_common.compile`.
  swift/internal/swift_module_alias.bzl
Labels: cla: yes

#208 Migrate `swift_{binary,test}` to `swift_common.compile`.
  swift/internal/linking.bzl
  swift/internal/swift_binary_test.bzl
Labels: cla: yes

#209 Migrate `swift_library` to `swift_common.compile`.
  swift/internal/swift_library.bzl
Labels: cla: yes

#207 Migrate `swift_{grpc,proto}_library` to `swift_common.compile`.
  swift/internal/swift_grpc_library.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
Labels: cla: yes

#210 Remove `swift_common.compile_as_{library,objects}`.
  swift/internal/api.bzl
Labels: cla: yes

#211 Fix `defines` being dropped after migration to the new API.
  swift/internal/swift_library.bzl
Labels: cla: yes

#212 New buildifier release includes some needed fixes.
  .bazelci/presubmit.yml
Labels: cla: yes

#215 Add CLI for dumping Swift toolchain bundle ids
  README.md
  tools/dump_toolchains/BUILD
  tools/dump_toolchains/dump_toolchains.sh
Labels: Import Ready, cla: yes

#213 Move link-related info out of `SwiftInfo` and into `CcInfo`.
  swift/internal/api.bzl
  swift/internal/attrs.bzl
  swift/internal/compiling.bzl
  swift/internal/deps.bzl
  swift/internal/linking.bzl
  swift/internal/providers.bzl
  swift/internal/swift_c_module_aspect.bzl
  swift/internal/swift_cc_libs_aspect.bzl
  swift/internal/swift_grpc_library.bzl
  swift/internal/swift_import.bzl
  swift/internal/swift_info_through_non_swift_targets_aspect.bzl
  swift/internal/swift_library.bzl
  swift/internal/swift_module_alias.bzl
  swift/internal/swift_proto_library.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
  swift/internal/utils.bzl
Labels: cla: yes

#217 Fix custom Swift toolchain when linking
  swift/internal/xcode_swift_toolchain.bzl
Labels: Import Ready, cla: yes

#216 Delete the `SwiftClangModuleInfo` provider.
  swift/internal/api.bzl
  swift/internal/attrs.bzl
  swift/internal/compiling.bzl
  swift/internal/legacy_swift_clang_module_info_aspect.bzl
  swift/internal/non_swift_target_aspect.bzl
  swift/internal/providers.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_c_module.bzl
  swift/internal/swift_grpc_library.bzl
  swift/internal/swift_import.bzl
  swift/internal/swift_library.bzl
  swift/internal/swift_module_alias.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
  swift/internal/utils.bzl
Labels: cla: yes

#220 Rollback of commit fbe8272de62e336b294340363beb6353e61bc1c7
  swift/internal/api.bzl
  swift/internal/attrs.bzl
  swift/internal/compiling.bzl
  swift/internal/legacy_swift_clang_module_info_aspect.bzl
  swift/internal/providers.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_c_module.bzl
  swift/internal/swift_c_module_aspect.bzl
  swift/internal/swift_grpc_library.bzl
  swift/internal/swift_import.bzl
  swift/internal/swift_library.bzl
  swift/internal/swift_module_alias.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
  swift/internal/utils.bzl
Labels: cla: yes

#222 Add config to test some deps at their heads.
  .bazelci/presubmit.yml
  .bazelci/update_workspace_to_deps_heads.sh
Labels: cla: yes

#223 Bump up the SwiftProtobuf and Swift gRPC versions to support Swift 5.
  swift/repositories.bzl
Labels: cla: yes

#221 Deprecate the `SwiftClangModuleInfo` provider.
  swift/internal/api.bzl
  swift/internal/attrs.bzl
  swift/internal/compiling.bzl
  swift/internal/legacy_swift_clang_module_info_aspect.bzl
  swift/internal/non_swift_target_aspect.bzl
  swift/internal/providers.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_c_module.bzl
  swift/internal/swift_grpc_library.bzl
  swift/internal/swift_import.bzl
  swift/internal/swift_info_through_non_swift_targets_aspect.bzl
  swift/internal/swift_library.bzl
  swift/internal/swift_module_alias.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
  swift/internal/utils.bzl
Labels: cla: yes

#226 Update the docs.
  doc/api.md
  doc/providers.md
  doc/rules.md
Labels: cla: yes

#228 Add missing "cpp" fragment to `swift_module_alias`.
  swift/internal/swift_module_alias.bzl
Labels: cla: yes

#230 Update rules_swift for --incompatible_enable_cc_toolchain_resolution
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: Import Ready, cla: yes

#231 Add ctx argument to cc_common.configure_features
  swift/internal/swift_import.bzl
Labels: cla: no

#232 Request cloning using COPYFILE_CLONE
  tools/common/file_system.cc
  tools/worker/work_processor.cc
Labels: Import Ready, cla: yes

#234 Avoid accidentally pulling in CcInfo providers from proto_library dependencies by not calling new_objc_provider in compiling.bzl.
  swift/internal/swift_proto_library.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
Labels: cla: yes

#235 Fix copts and linkopts relying on input files
  swift/internal/swift_library.bzl
Labels: Import Ready, cla: yes

#233 Set worker exit_code to failure if copying files fails
  tools/worker/work_processor.cc
Labels: Import Ready, cla: yes

#236 Remove the `-Wl,-z,notext` workaround.
  swift/internal/linking.bzl
Labels: cla: yes

#237 Support autoconf-like feature discovery for the Linux toolchain.
  swift/internal/swift_autoconfiguration.bzl
  swift/internal/swift_toolchain.bzl
  swift/repositories.bzl
Labels: cla: yes

#238 Get the C++ runtime to link from CcToolchainInfo, if necessary.
  swift/internal/linking.bzl
  swift/internal/swift_binary_test.bzl
Labels: cla: yes

#239 Remove the SwiftToolchainInfo.cc_toolchain_files field.
  swift/internal/linking.bzl
  swift/internal/providers.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
Labels: cla: yes

#242 Update protobuf to remove zlib dependency
  README.md
  WORKSPACE
  swift/repositories.bzl
  third_party/com_github_grpc_grpc_swift/BUILD.overlay
Labels: Import Ready, cla: yes
