Repository bazelbuild/rules_swift, pull requests merged in 2020-02, with the labels that each got.

#355 Add `swiftc -version` as input to Linux actions
  swift/internal/swift_autoconfiguration.bzl
  swift/internal/swift_toolchain.bzl
Labels: Import Ready, cla: yes

#387 Internal change
  swift/internal/compiling.bzl
  swift/internal/swift_grpc_library.bzl
Labels: cla: no

#389 bzl-visibility is no longer in the defaults.
  .bazelci/presubmit.yml
Labels: cla: yes

#390 Require the `swift_module` tag on `cc_library` targets that are
  swift/internal/module_maps.bzl
  swift/internal/non_swift_target_aspect.bzl
  test/fixtures/private_deps/BUILD
Labels: cla: yes

#392 Automated rollback of commit 5c988d7e7a607a2f7eb18a8755b72b01bf1edbbb.
  swift/internal/module_maps.bzl
  swift/internal/non_swift_target_aspect.bzl
  test/fixtures/private_deps/BUILD
Labels: cla: yes

#391 Allow `.swiftinterface` files to be emitted without library evolution enabled by adding `--features=swift.emit_swiftinterface` to the build.
  swift/internal/compiling.bzl
  swift/internal/swift_library.bzl
Labels: cla: yes

#393 Add a test to verify that `.swiftmodules` are propagated through non-Swift targets, like `objc_library`.
  test/BUILD
  test/fixtures/swift_through_non_swift/BUILD
  test/fixtures/swift_through_non_swift/Empty.h
  test/fixtures/swift_through_non_swift/Empty.swift
  test/swift_through_non_swift_tests.bzl
Labels: cla: yes

#394 Require the `swift_module` tag on `cc_library` targets that are
  swift/internal/module_maps.bzl
  swift/internal/non_swift_target_aspect.bzl
  test/fixtures/private_deps/BUILD
Labels: cla: yes

#395 Add `module_name` attribute to `swift_c_module`.
  swift/internal/swift_c_module.bzl
Labels: cla: yes

#397 Refactor the file containing `swift_common`.
  swift/internal/api.bzl
  swift/internal/attrs.bzl
  swift/internal/compiling.bzl
  swift/internal/feature_names.bzl
  swift/internal/features.bzl
  swift/internal/linking.bzl
  swift/internal/non_swift_target_aspect.bzl
  swift/internal/swift_autoconfiguration.bzl
  swift/internal/swift_binary_test.bzl
  swift/internal/swift_c_module.bzl
  swift/internal/swift_common.bzl
  swift/internal/swift_grpc_library.bzl
  swift/internal/swift_import.bzl
  swift/internal/swift_library.bzl
  swift/internal/swift_module_alias.bzl
  swift/internal/swift_protoc_gen_aspect.bzl
  swift/internal/swift_toolchain.bzl
  swift/internal/xcode_swift_toolchain.bzl
  swift/swift.bzl
Labels: cla: yes

#388 Allow cacheable_swiftmodule feature independent of compilation mode
  swift/internal/actions.bzl
  swift/internal/compiling.bzl
  swift/internal/toolchain_config.bzl
Labels: Import Ready, cla: yes

#399 Migrate Objc compile info to CcCompilationContext
  swift/internal/swift_library.bzl
  swift/internal/swift_module_alias.bzl
  swift/internal/utils.bzl
Labels: cla: no
